### PR TITLE
cleaned main.py

### PR DESCRIPTION
**Pull request by Namasteeee**

### CODE REVIEW

**Comment by Ezzaldeen97** [comment]
could you please wirte some description

**Comment by Namasteeee** [comment]
Hi @Ezzaldeen97,
Now its too late!
So i will write that here.
" This is a pull request"

**Comment by Ezzaldeen97** [comment]
@Namasteeee 
This didnt follow the guidelines.

**Comment by Namasteeee** [comment]
Thanks

**Pull request closed without merging**
